init:
    pnpm install

run:
    pnpm run dev

format:
    pnpm run format

check:
    pnpm run check

lint:
    pnpm run lint

update:
    pnpm update
    pnpm version patch --no-git-tag-version
    git add package.json package-lock.json
    git commit -m "chore(js/whimsy): update packages"
